export const LOAD_BLOG  = "LOAD_BLOG"
export const ADD_BLOG = "ADD_BLOG"
export const DELETE_BLOG = "DELETE_BLOG"
export const ADD_TO_HISTORY="ADD_TO_HISTORY"
export const SEARCH_BLOG = "SEARCH_BLOG"
export const REGISTER_USER  = "REGISTER_USER"
export const LOGIN_USER  = "LOGIN_USER"
export const LOGOUT_USER = "LOGOUT_USER"